name: scrape-eu-ft

on:
  schedule:
    - cron: "7 5 * * *"   # 05:07 UTC (~07:07 Europe/Paris) - quotidien
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "production"
      QUICK_MODE: "0"               # FULL RUN
      MAX_ENRICH_FUNDING: "2000"
      MAX_ENRICH_TENDERS: "1500"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium

      - name: Run scraper (FULL)
        run: npm start

      - name: Publish to docs/
        run: |
          git config user.name "gh-actions"
          git config user.email "actions@users.noreply.github.com"
          mkdir -p docs
          # index
          mv -f index.html docs/index.html || true
          # listes
          cp -f funding-list.* docs/ 2>/dev/null || true
          cp -f tenders-list.* docs/ 2>/dev/null || true
          # enriched
          cp -f funding_enriched.csv docs/ 2>/dev/null || true
          cp -f tenders_enriched.csv docs/ 2>/dev/null || true
          # (optionnel debug)
          # cp -f funding_raw.jsonl docs/ 2>/dev/null || true
          # cp -f tenders_raw.jsonl docs/ 2>/dev/null || true
          git add docs || true
          git commit -m "update lists & enriched (full) $(date -u +%FT%H:%M:%SZ)" || echo "no changes"
          git push
