name: scrape-eu-ft

on:
  schedule:
    - cron: "7 5 * * *"   # 05:07 UTC (~ 07:07 Europe/Paris) - exécution quotidienne
  workflow_dispatch: {}    # lancement manuel possible

permissions:
  contents: write          # nécessaire pour commit/push dans le dépôt

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        run: npm start

      # Publier les fichiers générés dans /docs (servi par GitHub Pages en Option A)
      - name: Publish to docs/
        run: |
          git config user.name "gh-actions"
          git config user.email "actions@users.noreply.github.com"
          mkdir -p docs
          # Page d'index
          mv -f index.html docs/index.html || true
          # Listes Funding & Tenders (HTML/CSV/JSON)
          cp -f funding-list.* docs/ 2>/dev/null || true
          cp -f tenders-list.* docs/ 2>/dev/null || true
          cp -f newsletter.html docs/ 2>/dev/null || true
          # Commit/push si changements
          git add docs || true
          git commit -m "update lists $(date -u +%FT%H:%M:%SZ)" || echo "no changes"
          git push
