name: scrape-eu-ft

on:
  schedule:
    - cron: "7 5 * * *"   # 05:07 UTC ~ 07:07 Paris
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install
      - run: npx playwright install --with-deps chromium
      - run: npm start

      - name: Publish to docs/
        run: |
          git config user.name "gh-actions"
          git config user.email "actions@users.noreply.github.com"
          mkdir -p docs
          mv -f list.html docs/index.html || true
          cp -f list.csv list.json docs/ 2>/dev/null || true
          git add docs list.* || true
          git commit -m "update list $(date -u +%F)" || echo "no changes"
          git push
