name: scrape-eu-ft-quick

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "production"
      QUICK_MODE: "1"           # 2 pages + limites réduites
      MAX_ENRICH_FUNDING: "30"
      MAX_ENRICH_TENDERS: "30"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium

      - name: Run scraper (QUICK)
        run: npm start

      - name: Publish to docs/ (quick)
        run: |
          git config user.name "gh-actions"
          git config user.email "actions@users.noreply.github.com"
          mkdir -p docs
          mv -f index.html docs/index.html || true
          cp -f funding-list.* docs/ 2>/dev/null || true
          cp -f tenders-list.* docs/ 2>/dev/null || true
          cp -f funding_enriched.csv docs/ 2>/dev/null || true
          cp -f tenders_enriched.csv docs/ 2>/dev/null || true
          git add docs || true
          git commit -m "update lists & enriched (quick) $(date -u +%FT%H:%M:%SZ)" || echo "no changes"
          git push
